---
#Ansible playbook starts with ---
-
    hosts: redhat-dcr
    #Hosts name is the managed system name
    #Declared variable
    vars:
        container_name: myfirstdockercontainer
        container_image: piyush1607kr/demoapp
    
    #Tasks will starts from here
    tasks: 
        - name: Update all installed packages using YUM module
          yum:
            name: '*'
            state: latest
            update_cache: yes
            update_only: yes
        - name: Install yum utils
          yum:
            name: "{{ item }}"
            state: latest

          with_items:
          - yum-utils
          - device-mapper-persistent-data

        - name: Add docker repo
          yum_repository:
            name: docker
            description: Docker repo
            baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
        - name: Adding GPG key
          rpm_key:
            key: /path/to/RPM-GPG-KEY.dag.txt
            fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35s
        - name: Download docker engine
          yum: 
            name: docker-ce 
            state: latest 
            update_cache: true 
        - name: Start docker
          service:
            name: docker 
            state: started
        - name: download the docker image
          docker_image:
            name: "{{container_image}}"
            source: pull 
        - name: run the docker container 
          docker_container:
            name: "{{container_name}}"
            image: "{{container_image}}"
            command: "{{default_container_command}}"
    


